name: Deployment

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest

    steps:
    - id: deployment
      name: Deployment
      uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: ${{ secret.AWS_REGION }}
        aws_elb_app_port: 3000
        env_ghs: ${{ .secrets.ENV }}
