name: Deployment

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types: [completed]

jobs:
  Deploy-EC2:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - id: deployment
      name: Deployment
      uses: peterkimzz/aws-ssm-send-command@v1.1.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
        command: |
            echo ${{ secrets.ENV }} > .env
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -af
